name: pixura-contracts
version: "0.2.0.0"
category: Web
author: Charles Crain
maintainer: craincharles@gmail.com
copyright: Pixura
license: BSD3
github: Pixura/pixura-contracts
extra-source-files:
  - README.md
default-extensions:
  - ApplicativeDo
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators
dependencies:
  - base >=4.7 && <5
  - generics-sop
  - web3
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
    - Pixura.Contracts.ERC721
    - Pixura.Contracts.ERC721Old
    - Pixura.Contracts.Autoglyphs
    - Pixura.Contracts.CryptoPunks
    - Pixura.Contracts.ERC721Market
    - Pixura.Contracts.ERC20
    - Pixura.Contracts.PixuraNFT
    - Pixura.Contracts.PixuraNFTContractGenerator
    - Pixura.Contracts.ZeroX.EtherToken
    - Pixura.Contracts.ZeroX.ERC20Proxy
    - Pixura.Contracts.ZeroX.ERC721Proxy
    - Pixura.Contracts.ZeroX.Exchange
    - Pixura.Contracts.SuperRare
    - Pixura.Contracts.SuperRareV2
    - Pixura.Contracts.SuperRareMarketAuction
