resolver: lts-12.8

packages:
  - '.'
  - location:
      git: https://github.com/f-o-a-m/hs-web3
      commit: f23250203451d1697c963ea7dadec615abd0a08b
    extra-dep: true

extra-deps:
  - presburger-1.3.1
  - sized-0.2.1.1
  - equational-reasoning-0.5.0.0
  - monomorphic-0.0.3.3
  - type-natural-0.7.1.4
  - ghc-typelits-presburger-0.1.1.1
  - constraints-0.10.1
  - relapse-1.0.0.0
  - secp256k1-0.5.3
