resolver: lts-12.8

packages:
  - "."
  - location:
      git: https://github.com/charlescrain/hs-web3
      commit: ccc94b58cc84d73af16655aa82dade554c429f9c
    extra-dep: true

extra-deps:
  - presburger-1.3.1
  - sized-0.2.1.1
  - equational-reasoning-0.5.0.0
  - monomorphic-0.0.3.3
  - type-natural-0.7.1.4
  - ghc-typelits-presburger-0.1.1.1
  - constraints-0.10.1
  - relapse-1.0.0.0
  - secp256k1-0.5.3
